# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpparma_hello_world <- function() {
    .Call(`_sgspls_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_sgspls_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_sgspls_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_sgspls_rcpparma_bothproducts`, x)
}

softthresh <- function(Mx, lambda) {
    .Call(`_sgspls_softthresh`, Mx, lambda)
}

lambdazerosubgroup <- function(lambda, Mx, subgroupX, alpha1, alpha2) {
    .Call(`_sgspls_lambdazerosubgroup`, lambda, Mx, subgroupX, alpha1, alpha2)
}

sgssoftthresh <- function(Mx, subgroupX, lambda, alpha1, alpha2, g) {
    .Call(`_sgspls_sgssoftthresh`, Mx, subgroupX, lambda, alpha1, alpha2, g)
}

updataU <- function(Mx, groupX, subgroupX, lambda, alpha1, alpha2) {
    .Call(`_sgspls_updataU`, Mx, groupX, subgroupX, lambda, alpha1, alpha2)
}

